export const searchAllowlist = [
  { name: "product", description: "Single product by slug or identifier" },
  { name: "productSearch", description: "Main PLP / search results" },
  { name: "products", description: "Filtered/ordered product list" },
  { name: "productsByIdentifier", description: "Products by ID field + values" },
  { name: "productRecommendations", description: "Cross-sell / similar products" },
  { name: "sponsoredProducts", description: "Sponsored products for a search context" },
  { name: "facets", description: "Facets / filters for a search" },
  { name: "banners", description: "Search banners" },
  { name: "correction", description: "Typo correction for a search term" },
  { name: "searchSuggestions", description: "Suggested search terms" },
  { name: "autocomplete", description: "Autocomplete suggestions" },
  { name: "topSearches", description: "Top searched terms" },
  { name: "autocompleteSearchSuggestions", description: "Term + attribute suggestions" },
  { name: "productSuggestions", description: "Product suggestions for a term" },
  { name: "searchMetadata", description: "Search page metadata (may be unavailable on some accounts)" },
  { name: "searchURLsCount", description: "Search URL access stats" },
] as const;

export const ioAllowlist = [
  { name: "product", description: "Single product by slug/identifier" },
  { name: "productSearch", description: "Product search (legacy store-graphql shape)" },
  { name: "products", description: "Product list" },
  { name: "categories", description: "Category tree" },
  { name: "category", description: "Single category by id" },
  { name: "facets", description: "Facets for a query" },
  { name: "shipping", description: "Shipping simulation" },
  { name: "orderForm", description: "Current or specified orderForm" },
  { name: "order", description: "Shopper order by id (not admin OMS)" },
  { name: "orders", description: "Deprecated shopper orders list — prefer vtex.orders-graphql" },
  { name: "session", description: "Session fields" },
  { name: "profile", description: "Logged-in profile" },
  { name: "document", description: "Master Data document (limited)" },
  { name: "documents", description: "Master Data documents search (limited)" },
] as const;
